# Generated by Django 4.0.6 on 2022-07-10 16:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0002_users_avatar_users_department_users_job_title'),
    ]

    operations = [
        migrations.AddField(
            model_name='users',
            name='date_of_birth',
            field=models.DateField(blank=True, null=True, verbose_name='Дата рождения'),
        ),
    ]
