# Generated by Django 4.0.6 on 2022-07-11 19:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0003_users_date_of_birth'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='users',
            name='is_verified',
        ),
        migrations.AlterField(
            model_name='users',
            name='email',
            field=models.EmailField(max_length=150, unique=True, verbose_name='E-mail'),
        ),
    ]
