# Generated by Django 4.0.6 on 2022-07-14 06:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0005_alter_users_managers_alter_users_department_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='users',
            name='need_change_password',
            field=models.BooleanField(default=True, help_text='Оставьте включенным для автоматического перенаправления при первой авторизации нового пользователя на страницу изменения пароля', verbose_name='Требовать изменения пароля'),
        ),
    ]
