# Generated by Django 4.0.6 on 2022-07-14 16:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0006_users_need_change_password'),
    ]

    operations = [
        migrations.AlterField(
            model_name='users',
            name='need_change_password',
            field=models.BooleanField(default=True, help_text='Оставьте включенным для автоматического перенаправления нового пользователя при первой авторизации  на страницу изменения пароля', verbose_name='Требовать изменения пароля'),
        ),
    ]
