# Generated by Django 4.0.6 on 2022-07-16 14:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0009_alter_users_department_alter_users_is_active_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='users',
            name='is_manager',
            field=models.BooleanField(default=False, help_text='Руководитель сможет заводить новых сотрудников в системе, удалять их из системы, направлять на курсы повышения квалификации', verbose_name='Руководитель'),
        ),
    ]
