# Generated by Django 4.0.6 on 2022-07-18 09:16

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('news', '0003_alter_newscomments_options_alter_newslikes_news'),
    ]

    operations = [
        migrations.AlterField(
            model_name='newscomments',
            name='news',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='news_comments', to='news.news', verbose_name='Комментируемая новость'),
        ),
    ]
