# Generated by Django 4.0.6 on 2022-07-25 09:10

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('news', '0004_alter_newscomments_news'),
    ]

    operations = [
        migrations.AddField(
            model_name='news',
            name='users_love',
            field=models.ManyToManyField(blank=True, related_name='news_loves', to=settings.AUTH_USER_MODEL),
        ),
    ]
